controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_state_controller:
      type: joint_state_controller/JointStateController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - Left_Hand_Thumb_Flexion
      - Left_Hand_Thumb_Opposition
      - Left_Hand_Index_Finger_Distal
      - Left_Hand_Index_Finger_Proximal
      - Left_Hand_Middle_Finger_Distal
      - Left_Hand_Middle_Finger_Proximal
      - Left_Hand_Ring_Finger
      - Left_Hand_Pinky
      - Left_Hand_Finger_Spread
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
